language: node_js
sudo: false
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
before_script:
  - npm install -g bower polymer-cli@next
  - bower install
script:
  - xvfb-run npm test
