language: node_js

sudo: false

dist: trusty

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true

git:
  depth: 3

node_js:
  - '6'

before_script:
  - npm install -g bower polymer-cli@next firebase-tools
  - bower install
  - npm run lint
  - polymer build

script:
  - xvfb-run polymer test --expanded -l chrome,firefox
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --expanded --plugin sauce --skip-plugin local; fi

after_success:
  - ./scripts/deploy.sh $TRAVIS_BRANCH

cache:
  directories:
  - node_modules
  - bower_components
  - $HOME/.nvm
